version: '3'
services:
    nodejs:
        build: .
        restart: always
        ports:
            - 8080:8080
        volumes:
            - ./:/home/tss404
            - /home/tss404/node_modules
        depends_on:
            - mysql
    mysql:
        image: mysql:8.0.15
        restart: always
        ports:
            - 3306:3306
        volumes:
            - ./docker/data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        command: --default-authentication-plugin=mysql_native_password
    adminer:
        image: adminer:4.7.1
        restart: always
        ports:
            - 8081:8080